[package]
name = "whisky-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.7"
reqwest = "0.11.24"
tokio = { version = "1.36.0", features = ["full"]}
eyre = "0.6.12"
postgres = "0.19.7"
serde = "1.0.196"
serde_json = "1.0.113"
iflet = "0.1.0"
